spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  #    url: jdbc:h2:file:./sample
  h2:
    console:
      enabled: true
